/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.GiaoVienBLL;
import BLL.MonHocBLL;
import DTO.GiaoVien;
import DTO.MonHoc;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LNhutDuy
 */
public class GiaoVienGUI extends javax.swing.JPanel {
    ArrayList<GiaoVien> listGV;
    DefaultTableModel model;
    ArrayList<MonHoc> listMH;
    JFrame rootPane = new JFrame();
    /**
     * Creates new form GiaoVienGUI
     */
    
    public GiaoVienGUI() {
        initComponents();
    }

    public void showTableMH(ArrayList<MonHoc> list) {
        for(MonHoc mh:list) {
            model.addRow(new Object[]{
                mh.getMaMH(), mh.getTenMH()
            });
        }
    }
    
    public void showTableGV(ArrayList<GiaoVien> list) {
        for(GiaoVien GV:list) {
            String TT = "Còn Hoạt Động";
            if(GV.getTinhTrang()==0)
                TT = "Ngừng Hoạt Động";    
            model.addRow(new Object[]{
                GV.getMaGV(), GV.getTenGV(), GV.getTenMH(), GV.getNamSinh(), GV.getSDT(), GV.getDiaChi(), GV.getEmail(), TT
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_TenGV = new javax.swing.JTextField();
        txt_MaGV = new javax.swing.JTextField();
        sl_MH = new javax.swing.JComboBox<>();
        btn_HuyGV = new javax.swing.JButton();
        txt_SDTGV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_DCGV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_EMGV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_NSGV = new javax.swing.JTextField();
        sl_TT = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_GV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_ThemGV = new javax.swing.JButton();
        btn_SuaGV = new javax.swing.JButton();
        btn_XoaGV = new javax.swing.JButton();

        jPanel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel2PropertyChange(evt);
            }
        });

        jLabel3.setText("Mã GV:");

        jLabel4.setText("Tên GV:");

        jLabel5.setText("Bộ Môn:");

        txt_TenGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenGVActionPerformed(evt);
            }
        });

        txt_MaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaGVActionPerformed(evt);
            }
        });

        sl_MH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_MHActionPerformed(evt);
            }
        });

        btn_HuyGV.setText("Huỷ");
        btn_HuyGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyGVActionPerformed(evt);
            }
        });

        txt_SDTGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTGVActionPerformed(evt);
            }
        });

        jLabel6.setText("Số ĐT:");

        txt_DCGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DCGVActionPerformed(evt);
            }
        });

        jLabel7.setText("Địa Chỉ:");

        txt_EMGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EMGVActionPerformed(evt);
            }
        });

        jLabel8.setText("Email:");

        txt_NSGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NSGVActionPerformed(evt);
            }
        });

        sl_TT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_TTActionPerformed(evt);
            }
        });

        jLabel10.setText("Tình Trạng:");

        jLabel11.setText("Năm Sinh:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_NSGV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sl_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_HuyGV, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_TenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sl_MH, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_DCGV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_SDTGV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_EMGV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SDTGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_TenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_DCGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sl_MH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_EMGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_HuyGV))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sl_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NSGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addContainerGap())))
        );

        tbl_GV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_GV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_GVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_GV);

        btn_ThemGV.setText("Thêm");
        btn_ThemGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemGVActionPerformed(evt);
            }
        });

        btn_SuaGV.setText("Sửa");
        btn_SuaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaGVActionPerformed(evt);
            }
        });

        btn_XoaGV.setText("Xoá");
        btn_XoaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaGVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_XoaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemGV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_ThemGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SuaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenGVActionPerformed

    private void txt_MaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaGVActionPerformed

    private void sl_MHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_MHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_MHActionPerformed

    private void btn_HuyGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyGVActionPerformed
        txt_MaGV.setText("");
        txt_TenGV.setText("");
        txt_SDTGV.setText("");
        txt_EMGV.setText("");
        txt_DCGV.setText("");
        txt_NSGV.setText("");
        sl_TT.setSelectedItem("Còn Hoạt Động");
        txt_MaGV.setEnabled(true);
        btn_ThemGV.setEnabled(true);
        btn_SuaGV.setEnabled(false);
        btn_XoaGV.setEnabled(false);
    }//GEN-LAST:event_btn_HuyGVActionPerformed

    private void txt_SDTGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTGVActionPerformed

    private void txt_DCGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DCGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DCGVActionPerformed

    private void txt_EMGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EMGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EMGVActionPerformed

    private void txt_NSGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NSGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NSGVActionPerformed

    private void sl_TTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_TTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_TTActionPerformed

    private void tbl_GVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_GVMouseClicked
        int this_Row=tbl_GV.getSelectedRow();
        TableModel row_SL = tbl_GV.getModel();
        String MaGV_SL = row_SL.getValueAt(this_Row, 0).toString();
        String TenGV_SL = row_SL.getValueAt(this_Row, 1).toString();
        String TenMH = row_SL.getValueAt(this_Row, 2).toString();
        String NSGV_s_SL = row_SL.getValueAt(this_Row, 3).toString();
        String SDTGV_SL =  row_SL.getValueAt(this_Row, 4).toString();
        String DCGV_SL = row_SL.getValueAt(this_Row, 5).toString();
        String EMGV_SL = row_SL.getValueAt(this_Row, 6).toString();
        String TT_SL = row_SL.getValueAt(this_Row, 7).toString();
        txt_MaGV.setText(MaGV_SL);
        txt_TenGV.setText(TenGV_SL);
        txt_SDTGV.setText(SDTGV_SL);
        txt_EMGV.setText(EMGV_SL);
        txt_DCGV.setText(DCGV_SL);
        txt_NSGV.setText(NSGV_s_SL);
        txt_NSGV.setText(NSGV_s_SL);
        sl_TT.setSelectedItem(TT_SL);
        txt_MaGV.setEnabled(false);
        btn_ThemGV.setEnabled(false);
        btn_SuaGV.setEnabled(true);
        btn_XoaGV.setEnabled(true);
    }//GEN-LAST:event_tbl_GVMouseClicked

    private void btn_ThemGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemGVActionPerformed
        String MaGV_s = txt_MaGV.getText();
        String TenGV = txt_TenGV.getText();
        String TenMH = sl_MH.getSelectedItem().toString();
        String SDTGV =  txt_SDTGV.getText();
        String EMGV = txt_EMGV.getText();
        String DCGV = txt_DCGV.getText();
        String NSGV_s = txt_NSGV.getText();
        if(!"".equals(TenGV) && !"".equals(SDTGV) && !"".equals(EMGV) && !"".equals(DCGV) && !"".equals(NSGV_s) && !"".equals(TenMH)) {
            try {
                int MaGV = Integer.parseInt(txt_MaGV.getText());
                int NSGV = Integer.parseInt(txt_NSGV.getText());
                GiaoVien GV = new GiaoVien();
                GV.addGV(MaGV, TenGV, 0, NSGV, EMGV, SDTGV, DCGV);
                GV.setTenMH(TenMH);
                GiaoVienBLL GVBLL = new GiaoVienBLL();
                if(GVBLL.AddGV(GV)=="") {
                    JOptionPane.showMessageDialog(rootPane, "Đã Thêm Giáo Viên");
                    model.addRow(new Object[] {
                        GV.getMaGV(),
                        GV.getTenGV(),
                        GV.getTenMH(),
                        GV.getNamSinh(),
                        GV.getSDT(),
                        GV.getDiaChi(),
                        GV.getEmail()
                    });
                } else {
                    JOptionPane.showMessageDialog(rootPane, GVBLL.AddGV(GV));
                }
                txt_MaGV.setText("");
                txt_TenGV.setText("");
                txt_SDTGV.setText("");
                txt_EMGV.setText("");
                txt_DCGV.setText("");
                txt_NSGV.setText("");
                sl_TT.setSelectedItem("Còn Hoạt Động");
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "Mã giáo viên phải ở kiểu số nguyên");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin! Mã giáo viên phải lớn hơn 0!");
        }
    }//GEN-LAST:event_btn_ThemGVActionPerformed

    private void btn_SuaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaGVActionPerformed
        int MaGV_New = Integer.parseInt(txt_MaGV.getText());
        String TenGV = txt_TenGV.getText();
        String TenMH = sl_MH.getSelectedItem().toString();
        String SDTGV =  txt_SDTGV.getText();
        String EMGV = txt_EMGV.getText();
        String DCGV = txt_DCGV.getText();
        String NSGV_s = txt_NSGV.getText();
        String TinhTrang = sl_TT.getSelectedItem().toString();
        if(!"".equals(TenGV) && !"".equals(SDTGV) && !"".equals(EMGV) && !"".equals(DCGV) && !"".equals(NSGV_s) && !"".equals(TenMH)) {
            GiaoVien GV = new GiaoVien();
            GV.addGV(MaGV_New, TenGV, 0, Integer.parseInt(NSGV_s), EMGV, SDTGV, DCGV);
            GV.setTenMH(TenMH);
            int i=0;
            int TT=1;
            if(TinhTrang=="Ngừng Hoạt Động")
            TT=0;
            int this_Row=tbl_GV.getSelectedRow();
            GV.setTinhTrang(TT);
            String MaGV_t = txt_MaGV.getText();
            GiaoVienBLL GVBLL = new GiaoVienBLL();
            if(GVBLL.UpdateGV(GV)=="")
            {
                this.model.setValueAt(MaGV_t, this_Row, 0);
                this.model.setValueAt(TenGV, this_Row, 1);
                this.model.setValueAt(TenMH, this_Row, 2);
                this.model.setValueAt(NSGV_s, this_Row, 3);
                this.model.setValueAt(SDTGV, this_Row, 4);
                this.model.setValueAt(DCGV, this_Row, 5);
                this.model.setValueAt(EMGV, this_Row, 6);
                this.model.setValueAt(TinhTrang, this_Row, 7);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Sửa Giáo Viên Thất Bại");
            }
            txt_MaGV.setText("");
            txt_TenGV.setText("");
            txt_SDTGV.setText("");
            txt_EMGV.setText("");
            txt_DCGV.setText("");
            txt_NSGV.setText("");
            sl_TT.setSelectedItem("Còn Hoạt Động");
            btn_SuaGV.setEnabled(false);
            btn_XoaGV.setEnabled(false);
            txt_MaGV.setEnabled(true);
            btn_ThemGV.setEnabled(true);
        } else
        JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin!");

    }//GEN-LAST:event_btn_SuaGVActionPerformed

    private void btn_XoaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaGVActionPerformed
        int MaGV = Integer.parseInt(txt_MaGV.getText());
        int this_Row=tbl_GV.getSelectedRow();
        this.model.setValueAt("Ngừng Hoạt Động", this_Row, 7);
        JOptionPane.showMessageDialog(rootPane, new GiaoVienBLL().DelGV(MaGV));
    }//GEN-LAST:event_btn_XoaGVActionPerformed

    private void jPanel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel2PropertyChange
        btn_SuaGV.setEnabled(false);
        btn_XoaGV.setEnabled(false);
        GiaoVienBLL GVGLL = new GiaoVienBLL();
        listGV = GVGLL.ShowDSGV();
        model = (DefaultTableModel) tbl_GV.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã Giáo Viên","Tên Giáo Viên", "Tên Môn Học", "Năm Sinh", "Số Điện Thoại", "Địa Chỉ", "Email", "Tình Trạng"
        });
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        model.removeRow(i);
        listMH = new MonHocBLL().ShowDSMH();
        sl_MH.removeAllItems();
        for(MonHoc MH: listMH) {
            sl_MH.addItem(MH.getTenMH());
        }
        sl_TT.removeAllItems();
        sl_TT.addItem("Còn Hoạt Động");
        sl_TT.addItem("Ngừng Hoạt Động");
        showTableGV(listGV);
    }//GEN-LAST:event_jPanel2PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HuyGV;
    private javax.swing.JButton btn_SuaGV;
    private javax.swing.JButton btn_ThemGV;
    private javax.swing.JButton btn_XoaGV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sl_MH;
    private javax.swing.JComboBox<String> sl_TT;
    private javax.swing.JTable tbl_GV;
    private javax.swing.JTextField txt_DCGV;
    private javax.swing.JTextField txt_EMGV;
    private javax.swing.JTextField txt_MaGV;
    private javax.swing.JTextField txt_NSGV;
    private javax.swing.JTextField txt_SDTGV;
    private javax.swing.JTextField txt_TenGV;
    // End of variables declaration//GEN-END:variables
}
