/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.GiaoVienBLL;
import BLL.KhoiBLL;
import BLL.LopBLL;
import DTO.GiaoVien;
import DTO.Khoi;
import DTO.Lop;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LNhutDuy
 */
public class LopKhoiGUI extends javax.swing.JPanel {
    ArrayList<GiaoVien> listGV;
    ArrayList<Khoi> listKhoi;
    ArrayList<Lop> listLop;
    DefaultTableModel model;
    DefaultTableModel model2;
    JFrame rootPane = new JFrame();
    /**
     * Creates new form LopKhoiGUI
     */
    public LopKhoiGUI() {
        initComponents();
    }
    
    public void showTableKhoi(ArrayList<Khoi> list) {
        for(Khoi K:list) {
            model2.addRow(new Object[]{
                K.getTenKhoi()
            });
        }
    }

    public void showTableLop(ArrayList<Lop> list) {
        String GiaoVien = "";
        for(Lop Lop:list) {
            GiaoVien = "";
            if(Lop.getMaGVCN()!=0)
                GiaoVien = Lop.getMaGVCN()+"-"+Lop.getTenGVCN();
            model.addRow(new Object[]{
                    Lop.getMaLop(), Lop.getTenLop(), Lop.getTenKhoi(), GiaoVien
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_TenLop = new javax.swing.JTextField();
        txt_MaLop = new javax.swing.JTextField();
        sl_Khoi = new javax.swing.JComboBox<>();
        btn_Lop = new javax.swing.JButton();
        sl_GVCN = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btn_ThemLop = new javax.swing.JButton();
        btn_SuaLop = new javax.swing.JButton();
        btn_XoaLop = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_Khoi = new javax.swing.JTextField();
        btn_XoaKhoi = new javax.swing.JButton();
        btn_ThemKhoi = new javax.swing.JButton();
        btn_HuyKhoi = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Khoi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Lop = new javax.swing.JTable();

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
        });
        jPanel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel5PropertyChange(evt);
            }
        });

        jLabel9.setText("Mã Lớp:");

        jLabel12.setText("Tên Lớp:");

        jLabel13.setText("Khối:");

        txt_TenLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenLopActionPerformed(evt);
            }
        });

        txt_MaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaLopActionPerformed(evt);
            }
        });

        sl_Khoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_KhoiActionPerformed(evt);
            }
        });

        btn_Lop.setText("Huỷ");
        btn_Lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LopActionPerformed(evt);
            }
        });

        sl_GVCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_GVCNActionPerformed(evt);
            }
        });

        jLabel19.setText("GVCN:");

        btn_ThemLop.setText("Thêm");
        btn_ThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLopActionPerformed(evt);
            }
        });

        btn_SuaLop.setText("Sửa");
        btn_SuaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLopActionPerformed(evt);
            }
        });

        btn_XoaLop.setText("Xoá");
        btn_XoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btn_Lop, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_TenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sl_Khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_XoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SuaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(sl_GVCN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl_Khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl_GVCN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Lop)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_ThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SuaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setToolTipText("");

        jLabel14.setText("Khối: ");

        txt_Khoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KhoiActionPerformed(evt);
            }
        });

        btn_XoaKhoi.setText("Xoá");
        btn_XoaKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaKhoiActionPerformed(evt);
            }
        });

        btn_ThemKhoi.setText("Thêm");
        btn_ThemKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKhoiActionPerformed(evt);
            }
        });

        btn_HuyKhoi.setText("Huỷ");
        btn_HuyKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyKhoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_Khoi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 76, Short.MAX_VALUE)
                        .addComponent(btn_HuyKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_XoaKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_ThemKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_XoaKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_HuyKhoi)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_Khoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_Khoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Khoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhoiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Khoi);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbl_Lop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LopMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Lop);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenLopActionPerformed

    private void txt_MaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaLopActionPerformed

    private void sl_KhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_KhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_KhoiActionPerformed

    private void btn_LopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LopActionPerformed
        sl_GVCN.removeItem("Không Thay Đổi");
        txt_TenLop.setText("");
        sl_GVCN.setSelectedItem("Để Sau");
        btn_ThemLop.setEnabled(true);
        btn_SuaLop.setEnabled(false);
        btn_XoaLop.setEnabled(false);
    }//GEN-LAST:event_btn_LopActionPerformed

    private void sl_GVCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_GVCNActionPerformed

    }//GEN-LAST:event_sl_GVCNActionPerformed

    private void btn_ThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLopActionPerformed
        String MaLop_s = txt_MaLop.getText();
        String TenLop = txt_TenLop.getText();
        String GiaoVien = sl_GVCN.getSelectedItem().toString();
        int TenKhoi = Integer.parseInt(sl_Khoi.getSelectedItem().toString());
        if(!"".equals(MaLop_s) && !"".equals(TenLop))
        {
            int MaGVCN = -1;
            String TenGVCN = "";
            int MaLop = Integer.parseInt(MaLop_s);
            if(GiaoVien.indexOf("-")!=-1) {
                String[] TTGV = GiaoVien.split("-");
                MaGVCN = Integer.parseInt(TTGV[0]);
                TenGVCN = TTGV[1];
            } else
            GiaoVien = "";
            Lop L = new Lop(MaLop, TenLop, TenKhoi, MaGVCN);
            L.setTenGVCN(TenGVCN);
            LopBLL LBLL = new LopBLL();

            if("".equals(LBLL.addLop(L))) {
                model.addRow(new Object[]{
                    MaLop, TenLop, TenKhoi, GiaoVien
                });
                JOptionPane.showMessageDialog(rootPane, "Đã thêm lớp");
                if(!"Để sau".equals(GiaoVien))
                sl_GVCN.removeItem(MaGVCN+"-"+TenGVCN);
            } else
            JOptionPane.showMessageDialog(rootPane, LBLL.addLop(L));

        }
        else
        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
    }//GEN-LAST:event_btn_ThemLopActionPerformed

    private void btn_SuaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLopActionPerformed
        String MaLop_s = txt_MaLop.getText();
        String TenLop = txt_TenLop.getText();
        String GiaoVien = sl_GVCN.getSelectedItem().toString();
        int TenKhoi = Integer.parseInt(sl_Khoi.getSelectedItem().toString());
        int this_Row = tbl_Lop.getSelectedRow();
        if(!"".equals(MaLop_s) && !"".equals(TenLop))
        {
            int MaGVCN = -1;
            String TenGVCN = "";
            int MaLop = Integer.parseInt(MaLop_s);
            if(GiaoVien.indexOf("-")!=-1) {
                String[] TTGV = GiaoVien.split("-");
                MaGVCN = Integer.parseInt(TTGV[0]);
                TenGVCN = TTGV[1];
            } else if (GiaoVien=="Không Thay Đổi") {
                MaGVCN = -2;
            } else
            GiaoVien="";
            Lop L = new Lop(MaLop, TenLop, TenKhoi, MaGVCN);
            L.setTenGVCN(TenGVCN);
            LopBLL LBLL = new LopBLL();
            if(LBLL.updateLop(L)=="") {
                model.setValueAt(L.getTenLop(), this_Row, 1);
                model.setValueAt(L.getTenKhoi(), this_Row, 2);
                if(MaGVCN != -2) {
                    model.setValueAt(GiaoVien, this_Row, 3);
                }
                ArrayList<GiaoVien> listGVCCN = new GiaoVienBLL().ShowDSGV_CCN();
                sl_GVCN.removeAllItems();
                sl_GVCN.addItem("Để Sau");
                for(GiaoVien GV: listGVCCN) {
                    sl_GVCN.addItem(GV.getMaGV()+"-"+GV.getTenGV());
                }
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
                sl_GVCN.removeItem("Không Thay Đổi");
                txt_TenLop.setText("");
                sl_GVCN.setSelectedItem("Để Sau");
                btn_ThemLop.setEnabled(true);
                btn_SuaLop.setEnabled(false);
                btn_XoaLop.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, LBLL.updateLop(L));
            }
        } else
        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
    }//GEN-LAST:event_btn_SuaLopActionPerformed

    private void btn_XoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLopActionPerformed
        txt_TenLop.setText("");
        sl_GVCN.setSelectedItem("Để Sau");
        btn_ThemLop.setEnabled(true);
        btn_SuaLop.setEnabled(false);
        btn_XoaLop.setEnabled(false);
        int MaLop = Integer.parseInt(txt_MaLop.getText());
        int this_Row = tbl_Lop.getSelectedRow();
        String GiaoVien = model.getValueAt(this_Row, 3).toString();
        int MaGVCN = -1;
        if(GiaoVien.indexOf("-")!=-1)
        MaGVCN = Integer.parseInt(GiaoVien.split("-")[0]);

        LopBLL LBLL = new LopBLL();
        if("".equals(LBLL.DelLop(MaLop, MaGVCN)))
        {
            ArrayList<GiaoVien> listGVCCN = new GiaoVienBLL().ShowDSGV_CCN();
            sl_GVCN.removeAllItems();
            sl_GVCN.addItem("Để Sau");
            for(GiaoVien GV: listGVCCN) {
                sl_GVCN.addItem(GV.getMaGV()+"-"+GV.getTenGV());
            }
            model.removeRow(this_Row);
        }
        JOptionPane.showMessageDialog(rootPane, LBLL.DelLop(MaLop, MaGVCN));
    }//GEN-LAST:event_btn_XoaLopActionPerformed

    private void txt_KhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KhoiActionPerformed

    private void btn_XoaKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaKhoiActionPerformed
        int K = Integer.parseInt(txt_Khoi.getText());
        KhoiBLL KBLL = new KhoiBLL();
        int this_Row = tbl_Khoi.getSelectedRow();
        if(KBLL.delKhoi(K)=="") {
            model2.removeRow(this_Row);
            btn_ThemKhoi.setEnabled(true);
            btn_XoaKhoi.setEnabled(false);
            txt_Khoi.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Xoá thành công");
        } else
        JOptionPane.showMessageDialog(rootPane, KBLL.delKhoi(K));
    }//GEN-LAST:event_btn_XoaKhoiActionPerformed

    private void btn_ThemKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKhoiActionPerformed
        if(!"".equals(txt_Khoi.getText())) {
            try {
                int K = Integer.parseInt(txt_Khoi.getText());
                KhoiBLL KhoiBLL = new KhoiBLL();
                if(KhoiBLL.addKhoi(K)=="")
                {
                    if(0<K && K<13) {
                        model2.addRow(new Object[]{
                            K
                        });
                        JOptionPane.showMessageDialog(rootPane, "Đã Thêm Khối");
                    } else
                    JOptionPane.showMessageDialog(rootPane, "Tên Khối Không Hợp Lệ");
                }
                else
                JOptionPane.showMessageDialog(rootPane, KhoiBLL.addKhoi(K));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Tên Khối Phải Kiểu Số Nguyên!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_ThemKhoiActionPerformed

    private void btn_HuyKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyKhoiActionPerformed
        txt_Khoi.setText("");
        txt_Khoi.setEnabled(true);
        btn_ThemKhoi.setEnabled(true);
        btn_XoaKhoi.setEnabled(false);
    }//GEN-LAST:event_btn_HuyKhoiActionPerformed

    private void tbl_KhoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhoiMouseClicked
        int this_Row=tbl_Khoi.getSelectedRow();
        TableModel row_SL = tbl_Khoi.getModel();
        String Khoi = row_SL.getValueAt(this_Row, 0).toString();
        txt_Khoi.setText(Khoi);
        btn_ThemKhoi.setEnabled(false);
        btn_XoaKhoi.setEnabled(true);
        txt_Khoi.setEnabled(false);
    }//GEN-LAST:event_tbl_KhoiMouseClicked

    private void tbl_LopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LopMouseClicked
        int this_Row = tbl_Lop.getSelectedRow();
        TableModel row_SL = tbl_Lop.getModel();
        sl_GVCN.removeItem("Không Thay Đổi");
        sl_GVCN.addItem("Không Thay Đổi");
        txt_MaLop.setText(row_SL.getValueAt(this_Row, 0).toString());
        txt_TenLop.setText(row_SL.getValueAt(this_Row, 1).toString());
        sl_GVCN.setSelectedItem("Không Thay Đổi");
        sl_Khoi.setSelectedItem(row_SL.getValueAt(this_Row, 2).toString());
        btn_ThemLop.setEnabled(false);
        btn_SuaLop.setEnabled(true);
        btn_XoaLop.setEnabled(true);
    }//GEN-LAST:event_tbl_LopMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel5PropertyChange
        //Show Khối
        btn_XoaKhoi.setEnabled(false);
        listKhoi = new KhoiBLL().showDSKhoi();
        model2 = (DefaultTableModel) tbl_Khoi.getModel();
        model2.setColumnIdentifiers(new Object[]{
            "Tên Khối"
        });
        int rowCount = model2.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        model2.removeRow(i);
        showTableKhoi(listKhoi);

        //Show Lớp
        txt_MaLop.setEnabled(false);
        txt_MaLop.setText(new LopBLL().creaMaLop()+"");
        btn_SuaLop.setEnabled(false);
        btn_XoaLop.setEnabled(false);
        listLop = new LopBLL().showDSLop();
        model = (DefaultTableModel) tbl_Lop.getModel();
        model.setColumnIdentifiers(new Object[] {
            "Mã Lớp", "Tên Lớp", "Khối", "Giáo Viên Chủ Nhiệm"
        });
        rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        model.removeRow(i);
        showTableLop(listLop);
        //SHOW select Khoi
        ArrayList<Khoi> listK = new KhoiBLL().showDSKhoi();
        sl_Khoi.removeAllItems();
        for(Khoi K: listK) {
            sl_Khoi.addItem(K.getTenKhoi()+"");
        }
        //SHOW select GV
        ArrayList<GiaoVien> listGVCCN = new GiaoVienBLL().ShowDSGV_CCN();
        sl_GVCN.removeAllItems();
        sl_GVCN.addItem("Để Sau");
        for(GiaoVien GV: listGVCCN) {
            sl_GVCN.addItem(GV.getMaGV()+"-"+GV.getTenGV());
        }

    }//GEN-LAST:event_jPanel5PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HuyKhoi;
    private javax.swing.JButton btn_Lop;
    private javax.swing.JButton btn_SuaLop;
    private javax.swing.JButton btn_ThemKhoi;
    private javax.swing.JButton btn_ThemLop;
    private javax.swing.JButton btn_XoaKhoi;
    private javax.swing.JButton btn_XoaLop;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> sl_GVCN;
    private javax.swing.JComboBox<String> sl_Khoi;
    private javax.swing.JTable tbl_Khoi;
    private javax.swing.JTable tbl_Lop;
    private javax.swing.JTextField txt_Khoi;
    private javax.swing.JTextField txt_MaLop;
    private javax.swing.JTextField txt_TenLop;
    // End of variables declaration//GEN-END:variables
}
