/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author LNhutDuy
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        this.setLocationRelativeTo(null);  
        setContent control = new setContent(jpn_content);
        control.setCT(jpn_QLGV , jlb_GV, "GV");        
        List<DanhMuc> listDM = new ArrayList<>();
        listDM.add(new DanhMuc("GV", jpn_QLGV, jlb_GV));
        listDM.add(new DanhMuc("MH", jpn_QLMH, jlb_MH));
        listDM.add(new DanhMuc("LK", jpn_QLLK, jlb_LK));
        control.addEvent(listDM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbn_menu = new javax.swing.JPanel();
        jpn_QLMH = new javax.swing.JPanel();
        jlb_MH = new javax.swing.JLabel();
        jpn_QLGV = new javax.swing.JPanel();
        jlb_GV = new javax.swing.JLabel();
        jpn_QLLK = new javax.swing.JPanel();
        jlb_LK = new javax.swing.JLabel();
        jpn_content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn_QLMH.setBackground(new java.awt.Color(250, 225, 170));
        jpn_QLMH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlb_MH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlb_MH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_MH.setText("Quản Lý Môn Học");
        jlb_MH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlb_MH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_MHMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_QLMHLayout = new javax.swing.GroupLayout(jpn_QLMH);
        jpn_QLMH.setLayout(jpn_QLMHLayout);
        jpn_QLMHLayout.setHorizontalGroup(
            jpn_QLMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QLMHLayout.createSequentialGroup()
                .addComponent(jlb_MH, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpn_QLMHLayout.setVerticalGroup(
            jpn_QLMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb_MH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jpn_QLGV.setBackground(new java.awt.Color(250, 225, 170));
        jpn_QLGV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpn_QLGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_QLGVMouseClicked(evt);
            }
        });

        jlb_GV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlb_GV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_GV.setText("Quản Lý Giáo Viên");
        jlb_GV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jpn_QLGVLayout = new javax.swing.GroupLayout(jpn_QLGV);
        jpn_QLGV.setLayout(jpn_QLGVLayout);
        jpn_QLGVLayout.setHorizontalGroup(
            jpn_QLGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb_GV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        jpn_QLGVLayout.setVerticalGroup(
            jpn_QLGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb_GV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jpn_QLLK.setBackground(new java.awt.Color(250, 225, 170));
        jpn_QLLK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlb_LK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlb_LK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_LK.setText("Quản Lý Lớp - Khối");
        jlb_LK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlb_LK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_LKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_QLLKLayout = new javax.swing.GroupLayout(jpn_QLLK);
        jpn_QLLK.setLayout(jpn_QLLKLayout);
        jpn_QLLKLayout.setHorizontalGroup(
            jpn_QLLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_QLLKLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlb_LK, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpn_QLLKLayout.setVerticalGroup(
            jpn_QLLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb_LK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jbn_menuLayout = new javax.swing.GroupLayout(jbn_menu);
        jbn_menu.setLayout(jbn_menuLayout);
        jbn_menuLayout.setHorizontalGroup(
            jbn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbn_menuLayout.createSequentialGroup()
                .addComponent(jpn_QLMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_QLGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_QLLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jbn_menuLayout.setVerticalGroup(
            jbn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbn_menuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jbn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_QLMH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QLGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QLLK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpn_contentLayout = new javax.swing.GroupLayout(jpn_content);
        jpn_content.setLayout(jpn_contentLayout);
        jpn_contentLayout.setHorizontalGroup(
            jpn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpn_contentLayout.setVerticalGroup(
            jpn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpn_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpn_QLGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_QLGVMouseClicked

    }//GEN-LAST:event_jpn_QLGVMouseClicked

    private void jlb_MHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_MHMouseClicked

    }//GEN-LAST:event_jlb_MHMouseClicked

    private void jlb_LKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_LKMouseClicked

    }//GEN-LAST:event_jlb_LKMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jbn_QLSV1;
    private javax.swing.JPanel jbn_QLSV2;
    private javax.swing.JPanel jbn_QLSV8;
    private javax.swing.JPanel jbn_QLSV9;
    private javax.swing.JPanel jbn_menu;
    private javax.swing.JLabel jlb_GV;
    private javax.swing.JLabel jlb_LK;
    private javax.swing.JLabel jlb_MH;
    private javax.swing.JPanel jpn_QLGV;
    private javax.swing.JPanel jpn_QLLK;
    private javax.swing.JPanel jpn_QLMH;
    private javax.swing.JPanel jpn_content;
    // End of variables declaration//GEN-END:variables
}
