/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.GiaoVienBLL;
import BLL.KhoiBLL;
import BLL.LopBLL;
import BLL.MonHocBLL;
import DAL.ConnMysql;
import DTO.GiaoVien;
import DTO.Khoi;
import DTO.Lop;
import DTO.MonHoc;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LNhutDuy
 */
public class QL_GV_L_MH extends javax.swing.JFrame {
    ArrayList<MonHoc> listMH;
    ArrayList<GiaoVien> listGV;
    ArrayList<Khoi> listKhoi;
    ArrayList<Lop> listLop;
    DefaultTableModel model;
    DefaultTableModel model2;
    public QL_GV_L_MH() {
        initComponents();
        this.setLocationRelativeTo(null);            
    }
    
    public void showTableMH(ArrayList<MonHoc> list) {
        for(MonHoc mh:list) {
            model.addRow(new Object[]{
                mh.getMaMH(), mh.getTenMH()
            });
        }
    }
    
    public void showTableGV(ArrayList<GiaoVien> list) {
        for(GiaoVien GV:list) {
            String TT = "Còn Hoạt Động";
            if(GV.getTinhTrang()==0)
                TT = "Ngừng Hoạt Động";    
            model.addRow(new Object[]{
                GV.getMaGV(), GV.getTenGV(), GV.getTenMH(), GV.getNamSinh(), GV.getSDT(), GV.getDiaChi(), GV.getEmail(), TT
            });
        }
    }
    
    public void showTableKhoi(ArrayList<Khoi> list) {
        for(Khoi K:list) {
            model2.addRow(new Object[]{
                K.getTenKhoi()
            });
        }
    }

    public void showTableLop(ArrayList<Lop> list) {
        String GiaoVien = "";
        for(Lop Lop:list) {
            GiaoVien = "";
            if(Lop.getMaGVCN()!=0)
                GiaoVien = Lop.getMaGVCN()+"-"+Lop.getTenGVCN();
            model.addRow(new Object[]{
                    Lop.getMaLop(), Lop.getTenLop(), Lop.getTenKhoi(), GiaoVien
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JScollPanel_MH = new javax.swing.JScrollPane();
        tbl_MH = new javax.swing.JTable();
        FromSX = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaMH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_TenMH = new javax.swing.JTextField();
        btn_HuyTTMH = new javax.swing.JButton();
        ThaoTac = new javax.swing.JPanel();
        btn_ThemMH = new javax.swing.JButton();
        btn_SuaMH = new javax.swing.JButton();
        btn_XoaMH = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_TenGV = new javax.swing.JTextField();
        txt_MaGV = new javax.swing.JTextField();
        sl_MH = new javax.swing.JComboBox<>();
        btn_HuyGV = new javax.swing.JButton();
        txt_SDTGV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_DCGV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_EMGV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_NSGV = new javax.swing.JTextField();
        sl_TT = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_GV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_ThemGV = new javax.swing.JButton();
        btn_SuaGV = new javax.swing.JButton();
        btn_XoaGV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_TenLop = new javax.swing.JTextField();
        txt_MaLop = new javax.swing.JTextField();
        sl_Khoi = new javax.swing.JComboBox<>();
        btn_Lop = new javax.swing.JButton();
        sl_GVCN = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btn_ThemLop = new javax.swing.JButton();
        btn_SuaLop = new javax.swing.JButton();
        btn_XoaLop = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_Khoi = new javax.swing.JTextField();
        btn_XoaKhoi = new javax.swing.JButton();
        btn_ThemKhoi = new javax.swing.JButton();
        btn_HuyKhoi = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Khoi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Lop = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        JScollPanel_MH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScollPanel_MHMouseClicked(evt);
            }
        });

        tbl_MH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_MH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_MHMouseClicked(evt);
            }
        });
        JScollPanel_MH.setViewportView(tbl_MH);

        FromSX.setForeground(new java.awt.Color(204, 204, 0));

        jLabel1.setText("Mã MH");

        txt_MaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaMHActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên MH");

        txt_TenMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenMHActionPerformed(evt);
            }
        });

        btn_HuyTTMH.setText("Huỷ");
        btn_HuyTTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyTTMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FromSXLayout = new javax.swing.GroupLayout(FromSX);
        FromSX.setLayout(FromSXLayout);
        FromSXLayout.setHorizontalGroup(
            FromSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FromSXLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FromSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(FromSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FromSXLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_HuyTTMH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(FromSXLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(FromSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_TenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        FromSXLayout.setVerticalGroup(
            FromSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FromSXLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(FromSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FromSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_HuyTTMH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btn_ThemMH.setText("Thêm");
        btn_ThemMH.setActionCommand("btn_ThemMH");
        btn_ThemMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemMHActionPerformed(evt);
            }
        });

        btn_SuaMH.setText("Sửa");
        btn_SuaMH.setActionCommand("btn_SuaMH");
        btn_SuaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaMHActionPerformed(evt);
            }
        });

        btn_XoaMH.setText("Xoá");
        btn_XoaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThaoTacLayout = new javax.swing.GroupLayout(ThaoTac);
        ThaoTac.setLayout(ThaoTacLayout);
        ThaoTacLayout.setHorizontalGroup(
            ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThaoTacLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_XoaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        ThaoTacLayout.setVerticalGroup(
            ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThaoTacLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_ThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FromSX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(JScollPanel_MH, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FromSX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThaoTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JScollPanel_MH, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Quản Lý Môn Học", jPanel1);

        jPanel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel2PropertyChange(evt);
            }
        });

        jLabel3.setText("Mã GV:");

        jLabel4.setText("Tên GV:");

        jLabel5.setText("Bộ Môn:");

        txt_TenGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenGVActionPerformed(evt);
            }
        });

        txt_MaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaGVActionPerformed(evt);
            }
        });

        sl_MH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_MHActionPerformed(evt);
            }
        });

        btn_HuyGV.setText("Huỷ");
        btn_HuyGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyGVActionPerformed(evt);
            }
        });

        txt_SDTGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTGVActionPerformed(evt);
            }
        });

        jLabel6.setText("Số ĐT:");

        txt_DCGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DCGVActionPerformed(evt);
            }
        });

        jLabel7.setText("Địa Chỉ:");

        txt_EMGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EMGVActionPerformed(evt);
            }
        });

        jLabel8.setText("Email:");

        txt_NSGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NSGVActionPerformed(evt);
            }
        });

        sl_TT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_TTActionPerformed(evt);
            }
        });

        jLabel10.setText("Tình Trạng:");

        jLabel11.setText("Năm Sinh:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_NSGV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sl_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_HuyGV, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_TenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sl_MH, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_DCGV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_SDTGV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_EMGV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SDTGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_TenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_DCGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sl_MH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_EMGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_HuyGV))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sl_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NSGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addContainerGap())))
        );

        tbl_GV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_GV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_GVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_GV);

        btn_ThemGV.setText("Thêm");
        btn_ThemGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemGVActionPerformed(evt);
            }
        });

        btn_SuaGV.setText("Sửa");
        btn_SuaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaGVActionPerformed(evt);
            }
        });

        btn_XoaGV.setText("Xoá");
        btn_XoaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaGVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_XoaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemGV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_ThemGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SuaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản Lý Giáo Viên", jPanel2);

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
        });
        jPanel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel5PropertyChange(evt);
            }
        });

        jLabel9.setText("Mã Lớp:");

        jLabel12.setText("Tên Lớp:");

        jLabel13.setText("Khối:");

        txt_TenLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenLopActionPerformed(evt);
            }
        });

        txt_MaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaLopActionPerformed(evt);
            }
        });

        sl_Khoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_KhoiActionPerformed(evt);
            }
        });

        btn_Lop.setText("Huỷ");
        btn_Lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LopActionPerformed(evt);
            }
        });

        sl_GVCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_GVCNActionPerformed(evt);
            }
        });

        jLabel19.setText("GVCN:");

        btn_ThemLop.setText("Thêm");
        btn_ThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLopActionPerformed(evt);
            }
        });

        btn_SuaLop.setText("Sửa");
        btn_SuaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLopActionPerformed(evt);
            }
        });

        btn_XoaLop.setText("Xoá");
        btn_XoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btn_Lop, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_TenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sl_Khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_XoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SuaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(sl_GVCN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl_Khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl_GVCN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Lop)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_ThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SuaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setToolTipText("");

        jLabel14.setText("Khối: ");

        txt_Khoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KhoiActionPerformed(evt);
            }
        });

        btn_XoaKhoi.setText("Xoá");
        btn_XoaKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaKhoiActionPerformed(evt);
            }
        });

        btn_ThemKhoi.setText("Thêm");
        btn_ThemKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKhoiActionPerformed(evt);
            }
        });

        btn_HuyKhoi.setText("Huỷ");
        btn_HuyKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyKhoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_Khoi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 76, Short.MAX_VALUE)
                        .addComponent(btn_HuyKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_XoaKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_ThemKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_XoaKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_HuyKhoi)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_Khoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_Khoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Khoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhoiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Khoi);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbl_Lop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LopMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Lop);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124))
        );

        jTabbedPane1.addTab("Quản Lý Lớp - Khối", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaMHActionPerformed

    private void txt_TenMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenMHActionPerformed

    private void btn_ThemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemMHActionPerformed
        if(!"".equals(txt_MaMH.getText()) && !"".equals(txt_TenMH.getText()))
        {
            try {
                int new_MaMH = Integer.parseInt(txt_MaMH.getText());
                String new_TenMH = txt_TenMH.getText();
                MonHoc MH = new MonHoc(new_MaMH, new_TenMH);                
                boolean check=false;
                MonHocBLL AddMH = new MonHocBLL();
                ;
                if(!"".equals(AddMH.AddMH(MH)))
                JOptionPane.showMessageDialog(rootPane, AddMH.AddMH(MH));
                else
                {
                    model.addRow(new Object[] {
                        MH.getMaMH(),
                        MH.getTenMH(),
                    });  
                listMH = new MonHocBLL().ShowDSMH();
                JOptionPane.showMessageDialog(rootPane, "Đã Thêm Môn Học");
                }
            } catch (NumberFormatException nfe) {
               JOptionPane.showMessageDialog(rootPane, "Mã môn học phải ở kiểu số nguyên");
            }
            txt_MaMH.setText("");
            txt_TenMH.setText("");
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Vui Lòng Nhập Đầy Đủ Thông Tin");
        }
    }//GEN-LAST:event_btn_ThemMHActionPerformed

    private void btn_SuaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaMHActionPerformed
        int MaMH_New = Integer.parseInt(txt_MaMH.getText());
        String TenMH_New = txt_TenMH.getText();
        if(TenMH_New!="") {
            MonHoc mh = new MonHoc(MaMH_New, TenMH_New);
            MonHocBLL MHBLL = new MonHocBLL(); 
            int this_Row= tbl_MH.getSelectedRow();
                String MaMH_t = txt_MaMH.getText();
                this.model.setValueAt(MaMH_t, this_Row, 0);
                this.model.setValueAt(TenMH_New, this_Row, 1);
                JOptionPane.showMessageDialog(rootPane, MHBLL.UpdateMH(mh));
        } else 
         JOptionPane.showMessageDialog(rootPane, "Vui Lòng Nhập Đầy Đủ Thông Tin");   
        
    }//GEN-LAST:event_btn_SuaMHActionPerformed

    private void btn_XoaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaMHActionPerformed
        int MaMH = Integer.parseInt(txt_MaMH.getText());
        int this_Row=tbl_GV.getSelectedRow();
        this.model.removeRow(this_Row);
        JOptionPane.showMessageDialog(rootPane, new MonHocBLL().DelMH(MaMH));        
    }//GEN-LAST:event_btn_XoaMHActionPerformed

    private void btn_HuyTTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyTTMHActionPerformed
        btn_SuaMH.setEnabled(false);
        btn_XoaMH.setEnabled(false);  
        txt_MaMH.setEnabled(true);
        btn_ThemMH.setEnabled(true);
        txt_MaMH.setText("");
        txt_TenMH.setText("");
    }//GEN-LAST:event_btn_HuyTTMHActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        txt_TenMH.setText("");
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void tbl_MHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_MHMouseClicked
        int this_Row=tbl_MH.getSelectedRow();
        System.out.println();
        TableModel row_SL = tbl_MH.getModel();
        String MaMH_SL = row_SL.getValueAt(this_Row, 0).toString();
        String TenMH_SL = row_SL.getValueAt(this_Row, 1).toString();
        txt_MaMH.setText(MaMH_SL);
        txt_TenMH.setText(TenMH_SL);
        txt_MaMH.setEnabled(false);
        btn_ThemMH.setEnabled(false);
        btn_SuaMH.setEnabled(true);
        btn_XoaMH.setEnabled(true);  
    }//GEN-LAST:event_tbl_MHMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        btn_SuaMH.setEnabled(false);     
        btn_XoaMH.setEnabled(false);    
        listMH = new MonHocBLL().ShowDSMH();
        model = (DefaultTableModel) tbl_MH.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã Môn Học","Tên Môn Học"
        });  
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
            model.removeRow(i);
        showTableMH(listMH);
    }//GEN-LAST:event_jPanel1PropertyChange

    private void JScollPanel_MHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JScollPanel_MHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JScollPanel_MHMouseClicked

    private void jPanel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel2PropertyChange
        btn_SuaGV.setEnabled(false);
        btn_XoaGV.setEnabled(false);
        GiaoVienBLL GVGLL = new GiaoVienBLL();
        listGV = GVGLL.ShowDSGV();
        model = (DefaultTableModel) tbl_GV.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã Giáo Viên","Tên Giáo Viên", "Tên Môn Học", "Năm Sinh", "Số Điện Thoại", "Địa Chỉ", "Email", "Tình Trạng"
        });
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        model.removeRow(i);
        listMH = new MonHocBLL().ShowDSMH();
        sl_MH.removeAllItems();
        for(MonHoc MH: listMH) {
            sl_MH.addItem(MH.getTenMH());
        }
        sl_TT.removeAllItems();
        sl_TT.addItem("Còn Hoạt Động");
        sl_TT.addItem("Ngừng Hoạt Động");
        showTableGV(listGV);
    }//GEN-LAST:event_jPanel2PropertyChange

    private void btn_XoaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaGVActionPerformed
        int MaGV = Integer.parseInt(txt_MaGV.getText());
        int this_Row=tbl_GV.getSelectedRow();
        this.model.setValueAt("Ngừng Hoạt Động", this_Row, 7);
        JOptionPane.showMessageDialog(rootPane, new GiaoVienBLL().DelGV(MaGV));  
    }//GEN-LAST:event_btn_XoaGVActionPerformed

    private void btn_SuaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaGVActionPerformed
        int MaGV_New = Integer.parseInt(txt_MaGV.getText());
        String TenGV = txt_TenGV.getText();
        String TenMH = sl_MH.getSelectedItem().toString();
        String SDTGV =  txt_SDTGV.getText();
        String EMGV = txt_EMGV.getText();
        String DCGV = txt_DCGV.getText();
        String NSGV_s = txt_NSGV.getText();
        String TinhTrang = sl_TT.getSelectedItem().toString();
        if(!"".equals(TenGV) && !"".equals(SDTGV) && !"".equals(EMGV) && !"".equals(DCGV) && !"".equals(NSGV_s) && !"".equals(TenMH)) {
            GiaoVien GV = new GiaoVien();
            GV.addGV(MaGV_New, TenGV, 0, Integer.parseInt(NSGV_s), EMGV, SDTGV, DCGV);
            GV.setTenMH(TenMH);
            int i=0;
            int TT=1;
            if(TinhTrang=="Ngừng Hoạt Động")
                TT=0;
            int this_Row=tbl_GV.getSelectedRow();
            GV.setTinhTrang(TT);
            String MaGV_t = txt_MaGV.getText();
            GiaoVienBLL GVBLL = new GiaoVienBLL();
            if(GVBLL.UpdateGV(GV)=="")
            {
                this.model.setValueAt(MaGV_t, this_Row, 0);
                this.model.setValueAt(TenGV, this_Row, 1);
                this.model.setValueAt(TenMH, this_Row, 2);
                this.model.setValueAt(NSGV_s, this_Row, 3);
                this.model.setValueAt(SDTGV, this_Row, 4);
                this.model.setValueAt(DCGV, this_Row, 5);
                this.model.setValueAt(EMGV, this_Row, 6);
                this.model.setValueAt(TinhTrang, this_Row, 7);
            }
            else 
            {
                JOptionPane.showMessageDialog(rootPane, "Sửa Giáo Viên Thất Bại");
            }
            txt_MaGV.setText("");
            txt_TenGV.setText("");
            txt_SDTGV.setText("");
            txt_EMGV.setText("");
            txt_DCGV.setText("");
            txt_NSGV.setText("");
            sl_TT.setSelectedItem("Còn Hoạt Động");
            btn_SuaGV.setEnabled(false);
            btn_XoaGV.setEnabled(false);  
            txt_MaGV.setEnabled(true);
            btn_ThemGV.setEnabled(true);
        } else 
           JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin!"); 

        
    }//GEN-LAST:event_btn_SuaGVActionPerformed

    private void btn_ThemGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemGVActionPerformed
        String MaGV_s = txt_MaGV.getText();
        String TenGV = txt_TenGV.getText();
        String TenMH = sl_MH.getSelectedItem().toString();
        String SDTGV =  txt_SDTGV.getText();
        String EMGV = txt_EMGV.getText();
        String DCGV = txt_DCGV.getText();
        String NSGV_s = txt_NSGV.getText();
        if(!"".equals(TenGV) && !"".equals(SDTGV) && !"".equals(EMGV) && !"".equals(DCGV) && !"".equals(NSGV_s) && !"".equals(TenMH)) {
            try {
                int MaGV = Integer.parseInt(txt_MaGV.getText());
                int NSGV = Integer.parseInt(txt_NSGV.getText());
                GiaoVien GV = new GiaoVien();
                GV.addGV(MaGV, TenGV, 0, NSGV, EMGV, SDTGV, DCGV);
                GV.setTenMH(TenMH);
                GiaoVienBLL GVBLL = new GiaoVienBLL();
                if(GVBLL.AddGV(GV)=="") {
                    JOptionPane.showMessageDialog(rootPane, "Đã Thêm Giáo Viên");
                    model.addRow(new Object[] {
                        GV.getMaGV(),
                        GV.getTenGV(),
                        GV.getTenMH(),
                        GV.getNamSinh(),
                        GV.getSDT(),
                        GV.getDiaChi(),
                        GV.getEmail()                        
                    });
                } else {
                    JOptionPane.showMessageDialog(rootPane, GVBLL.AddGV(GV));
                }
                txt_MaGV.setText("");
                txt_TenGV.setText("");
                txt_SDTGV.setText("");
                txt_EMGV.setText("");
                txt_DCGV.setText("");
                txt_NSGV.setText("");
                sl_TT.setSelectedItem("Còn Hoạt Động");
            } catch (NumberFormatException nfe) {
               JOptionPane.showMessageDialog(rootPane, "Mã giáo viên phải ở kiểu số nguyên");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin! Mã giáo viên phải lớn hơn 0!");
        }
    }//GEN-LAST:event_btn_ThemGVActionPerformed

    private void tbl_GVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_GVMouseClicked
        int this_Row=tbl_GV.getSelectedRow();
        TableModel row_SL = tbl_GV.getModel();
        String MaGV_SL = row_SL.getValueAt(this_Row, 0).toString();
        String TenGV_SL = row_SL.getValueAt(this_Row, 1).toString();
        String TenMH = row_SL.getValueAt(this_Row, 2).toString();
        String NSGV_s_SL = row_SL.getValueAt(this_Row, 3).toString();
        String SDTGV_SL =  row_SL.getValueAt(this_Row, 4).toString();
        String DCGV_SL = row_SL.getValueAt(this_Row, 5).toString();
        String EMGV_SL = row_SL.getValueAt(this_Row, 6).toString();
        String TT_SL = row_SL.getValueAt(this_Row, 7).toString();
        txt_MaGV.setText(MaGV_SL);
        txt_TenGV.setText(TenGV_SL);
        txt_SDTGV.setText(SDTGV_SL);
        txt_EMGV.setText(EMGV_SL);
        txt_DCGV.setText(DCGV_SL);
        txt_NSGV.setText(NSGV_s_SL);
        txt_NSGV.setText(NSGV_s_SL);
        sl_TT.setSelectedItem(TT_SL);
        txt_MaGV.setEnabled(false);
        btn_ThemGV.setEnabled(false);
        btn_SuaGV.setEnabled(true);
        btn_XoaGV.setEnabled(true);
    }//GEN-LAST:event_tbl_GVMouseClicked

    private void btn_HuyGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyGVActionPerformed
        txt_MaGV.setText("");
        txt_TenGV.setText("");
        txt_SDTGV.setText("");
        txt_EMGV.setText("");
        txt_DCGV.setText("");
        txt_NSGV.setText("");
        sl_TT.setSelectedItem("Còn Hoạt Động");
        txt_MaGV.setEnabled(true);
        btn_ThemGV.setEnabled(true);
        btn_SuaGV.setEnabled(false);
        btn_XoaGV.setEnabled(false);
    }//GEN-LAST:event_btn_HuyGVActionPerformed

    private void sl_MHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_MHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_MHActionPerformed

    private void txt_MaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaGVActionPerformed

    private void txt_TenGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenGVActionPerformed

    private void txt_SDTGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTGVActionPerformed

    private void txt_DCGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DCGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DCGVActionPerformed

    private void txt_EMGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EMGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EMGVActionPerformed

    private void txt_NSGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NSGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NSGVActionPerformed

    private void sl_TTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_TTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_TTActionPerformed

    private void txt_TenLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenLopActionPerformed

    private void txt_MaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaLopActionPerformed

    private void sl_KhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_KhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_KhoiActionPerformed

    private void btn_LopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LopActionPerformed
        sl_GVCN.removeItem("Không Thay Đổi");
        txt_TenLop.setText("");
        sl_GVCN.setSelectedItem("Để Sau");      
        btn_ThemLop.setEnabled(true);
        btn_SuaLop.setEnabled(false);
        btn_XoaLop.setEnabled(false);
    }//GEN-LAST:event_btn_LopActionPerformed

    private void tbl_LopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LopMouseClicked
        int this_Row = tbl_Lop.getSelectedRow();
        TableModel row_SL = tbl_Lop.getModel();
        sl_GVCN.removeItem("Không Thay Đổi");
        sl_GVCN.addItem("Không Thay Đổi");
        txt_MaLop.setText(row_SL.getValueAt(this_Row, 0).toString());
        txt_TenLop.setText(row_SL.getValueAt(this_Row, 1).toString());
        sl_GVCN.setSelectedItem("Không Thay Đổi");
        sl_Khoi.setSelectedItem(row_SL.getValueAt(this_Row, 2).toString());      
        btn_ThemLop.setEnabled(false);
        btn_SuaLop.setEnabled(true);
        btn_XoaLop.setEnabled(true);
    }//GEN-LAST:event_tbl_LopMouseClicked

    private void btn_ThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLopActionPerformed
        String MaLop_s = txt_MaLop.getText();
        String TenLop = txt_TenLop.getText();
        String GiaoVien = sl_GVCN.getSelectedItem().toString();
        int TenKhoi = Integer.parseInt(sl_Khoi.getSelectedItem().toString());
        if(!"".equals(MaLop_s) && !"".equals(TenLop))
        {   
            int MaGVCN = -1;
            String TenGVCN = "";
            int MaLop = Integer.parseInt(MaLop_s);
            if(GiaoVien.indexOf("-")!=-1) {
                String[] TTGV = GiaoVien.split("-");
                MaGVCN = Integer.parseInt(TTGV[0]);
                TenGVCN = TTGV[1];
            } else 
                GiaoVien = "";
            Lop L = new Lop(MaLop, TenLop, TenKhoi, MaGVCN);
            L.setTenGVCN(TenGVCN);
            LopBLL LBLL = new LopBLL();
            
            
            if("".equals(LBLL.addLop(L))) {
                model.addRow(new Object[]{
                    MaLop, TenLop, TenKhoi, GiaoVien
            });
                JOptionPane.showMessageDialog(rootPane, "Đã thêm lớp");
                if(!"Để sau".equals(GiaoVien))
                    sl_GVCN.removeItem(MaGVCN+"-"+TenGVCN);
            } else 
                JOptionPane.showMessageDialog(rootPane, LBLL.addLop(L));
                
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
    }//GEN-LAST:event_btn_ThemLopActionPerformed

    private void btn_SuaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLopActionPerformed
        String MaLop_s = txt_MaLop.getText();
        String TenLop = txt_TenLop.getText();
        String GiaoVien = sl_GVCN.getSelectedItem().toString();
        int TenKhoi = Integer.parseInt(sl_Khoi.getSelectedItem().toString());
        int this_Row = tbl_Lop.getSelectedRow();
        if(!"".equals(MaLop_s) && !"".equals(TenLop))
        {   
            int MaGVCN = -1;
            String TenGVCN = "";
            int MaLop = Integer.parseInt(MaLop_s);
            if(GiaoVien.indexOf("-")!=-1) {
                String[] TTGV = GiaoVien.split("-");
                MaGVCN = Integer.parseInt(TTGV[0]);
                TenGVCN = TTGV[1];
            } else if (GiaoVien=="Không Thay Đổi") {
                    MaGVCN = -2;
                } else    
                GiaoVien="";
            Lop L = new Lop(MaLop, TenLop, TenKhoi, MaGVCN);
            L.setTenGVCN(TenGVCN);
            LopBLL LBLL = new LopBLL();
            if(LBLL.updateLop(L)=="") {
                model.setValueAt(L.getTenLop(), this_Row, 1);
                model.setValueAt(L.getTenKhoi(), this_Row, 2);
                if(MaGVCN != -2) {
                    model.setValueAt(GiaoVien, this_Row, 3);
                }
                ArrayList<GiaoVien> listGVCCN = new GiaoVienBLL().ShowDSGV_CCN();
                sl_GVCN.removeAllItems();
                sl_GVCN.addItem("Để Sau");
                for(GiaoVien GV: listGVCCN) {
                    sl_GVCN.addItem(GV.getMaGV()+"-"+GV.getTenGV());
                }
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
                sl_GVCN.removeItem("Không Thay Đổi");
                txt_TenLop.setText("");
                sl_GVCN.setSelectedItem("Để Sau");      
                btn_ThemLop.setEnabled(true);
                btn_SuaLop.setEnabled(false);
                btn_XoaLop.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, LBLL.updateLop(L));
            }
        } else
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
    }//GEN-LAST:event_btn_SuaLopActionPerformed

    private void btn_XoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLopActionPerformed
        txt_TenLop.setText("");
        sl_GVCN.setSelectedItem("Để Sau");      
        btn_ThemLop.setEnabled(true);
        btn_SuaLop.setEnabled(false);
        btn_XoaLop.setEnabled(false);
        int MaLop = Integer.parseInt(txt_MaLop.getText());
        int this_Row = tbl_Lop.getSelectedRow();
        String GiaoVien = model.getValueAt(this_Row, 3).toString();
        int MaGVCN = -1; 
        if(GiaoVien.indexOf("-")!=-1)
            MaGVCN = Integer.parseInt(GiaoVien.split("-")[0]);
        
        LopBLL LBLL = new LopBLL();
        if("".equals(LBLL.DelLop(MaLop, MaGVCN)))
        {
            ArrayList<GiaoVien> listGVCCN = new GiaoVienBLL().ShowDSGV_CCN();
            sl_GVCN.removeAllItems();
            sl_GVCN.addItem("Để Sau");
            for(GiaoVien GV: listGVCCN) {
                sl_GVCN.addItem(GV.getMaGV()+"-"+GV.getTenGV());
            }
            model.removeRow(this_Row);
        }
        JOptionPane.showMessageDialog(rootPane, LBLL.DelLop(MaLop, MaGVCN));
    }//GEN-LAST:event_btn_XoaLopActionPerformed

    private void jPanel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel5PropertyChange
        //Show Khối
        btn_XoaKhoi.setEnabled(false);
        listKhoi = new KhoiBLL().showDSKhoi();
        model2 = (DefaultTableModel) tbl_Khoi.getModel();
        model2.setColumnIdentifiers(new Object[]{
            "Tên Khối"
        });
        int rowCount = model2.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        model2.removeRow(i);        
        showTableKhoi(listKhoi);
        
        
        
        //Show Lớp
        txt_MaLop.setEnabled(false);
        txt_MaLop.setText(new LopBLL().creaMaLop()+"");
        btn_SuaLop.setEnabled(false);
        btn_XoaLop.setEnabled(false);
        listLop = new LopBLL().showDSLop();
        model = (DefaultTableModel) tbl_Lop.getModel();
        model.setColumnIdentifiers(new Object[] {
            "Mã Lớp", "Tên Lớp", "Khối", "Giáo Viên Chủ Nhiệm"
        });
        rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        model.removeRow(i);
        showTableLop(listLop);
        //SHOW select Khoi
        ArrayList<Khoi> listK = new KhoiBLL().showDSKhoi();
        sl_Khoi.removeAllItems();
        for(Khoi K: listK) {
            sl_Khoi.addItem(K.getTenKhoi()+"");
        }
        //SHOW select GV
        ArrayList<GiaoVien> listGVCCN = new GiaoVienBLL().ShowDSGV_CCN();
        sl_GVCN.removeAllItems();
        sl_GVCN.addItem("Để Sau");
        for(GiaoVien GV: listGVCCN) {
            sl_GVCN.addItem(GV.getMaGV()+"-"+GV.getTenGV());
        }
        
    }//GEN-LAST:event_jPanel5PropertyChange

    private void sl_GVCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_GVCNActionPerformed

    }//GEN-LAST:event_sl_GVCNActionPerformed

    private void txt_KhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KhoiActionPerformed

    private void btn_ThemKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKhoiActionPerformed
        if(!"".equals(txt_Khoi.getText())) {
            try {
                int K = Integer.parseInt(txt_Khoi.getText());
                KhoiBLL KhoiBLL = new KhoiBLL();
                if(KhoiBLL.addKhoi(K)=="")
                {
                    if(0<K && K<13) {
                        model2.addRow(new Object[]{
                            K
                        });
                        JOptionPane.showMessageDialog(rootPane, "Đã Thêm Khối");
                    } else 
                        JOptionPane.showMessageDialog(rootPane, "Tên Khối Không Hợp Lệ");
                }
                else
                    JOptionPane.showMessageDialog(rootPane, KhoiBLL.addKhoi(K));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Tên Khối Phải Kiểu Số Nguyên!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_ThemKhoiActionPerformed

    private void btn_XoaKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaKhoiActionPerformed
        int K = Integer.parseInt(txt_Khoi.getText());
        KhoiBLL KBLL = new KhoiBLL();
        int this_Row = tbl_Khoi.getSelectedRow();
        if(KBLL.delKhoi(K)=="") {
            model2.removeRow(this_Row);
            btn_ThemKhoi.setEnabled(true);
            btn_XoaKhoi.setEnabled(false);
            txt_Khoi.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Xoá thành công");
        } else 
            JOptionPane.showMessageDialog(rootPane, KBLL.delKhoi(K));
    }//GEN-LAST:event_btn_XoaKhoiActionPerformed

    private void btn_HuyKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyKhoiActionPerformed
        txt_Khoi.setText("");
        txt_Khoi.setEnabled(true);
        btn_ThemKhoi.setEnabled(true);
        btn_XoaKhoi.setEnabled(false);
    }//GEN-LAST:event_btn_HuyKhoiActionPerformed

    private void tbl_KhoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhoiMouseClicked
        int this_Row=tbl_Khoi.getSelectedRow();
        TableModel row_SL = tbl_Khoi.getModel();
        String Khoi = row_SL.getValueAt(this_Row, 0).toString();
        txt_Khoi.setText(Khoi);
        btn_ThemKhoi.setEnabled(false);
        btn_XoaKhoi.setEnabled(true);
        txt_Khoi.setEnabled(false);
    }//GEN-LAST:event_tbl_KhoiMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_GV_L_MH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_GV_L_MH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_GV_L_MH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_GV_L_MH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_GV_L_MH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FromSX;
    private javax.swing.JScrollPane JScollPanel_MH;
    private javax.swing.JPanel ThaoTac;
    private javax.swing.JButton btn_HuyGV;
    private javax.swing.JButton btn_HuyKhoi;
    private javax.swing.JButton btn_HuyTTMH;
    private javax.swing.JButton btn_Lop;
    private javax.swing.JButton btn_SuaGV;
    private javax.swing.JButton btn_SuaLop;
    private javax.swing.JButton btn_SuaMH;
    private javax.swing.JButton btn_ThemGV;
    private javax.swing.JButton btn_ThemKhoi;
    private javax.swing.JButton btn_ThemLop;
    private javax.swing.JButton btn_ThemMH;
    private javax.swing.JButton btn_XoaGV;
    private javax.swing.JButton btn_XoaKhoi;
    private javax.swing.JButton btn_XoaLop;
    private javax.swing.JButton btn_XoaMH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> sl_GVCN;
    private javax.swing.JComboBox<String> sl_Khoi;
    private javax.swing.JComboBox<String> sl_MH;
    private javax.swing.JComboBox<String> sl_TT;
    private javax.swing.JTable tbl_GV;
    private javax.swing.JTable tbl_Khoi;
    private javax.swing.JTable tbl_Lop;
    private javax.swing.JTable tbl_MH;
    private javax.swing.JTextField txt_DCGV;
    private javax.swing.JTextField txt_EMGV;
    private javax.swing.JTextField txt_Khoi;
    private javax.swing.JTextField txt_MaGV;
    private javax.swing.JTextField txt_MaLop;
    private javax.swing.JTextField txt_MaMH;
    private javax.swing.JTextField txt_NSGV;
    private javax.swing.JTextField txt_SDTGV;
    private javax.swing.JTextField txt_TenGV;
    private javax.swing.JTextField txt_TenLop;
    private javax.swing.JTextField txt_TenMH;
    // End of variables declaration//GEN-END:variables

}
